services:
  vakilsahab-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    container_name: vakilsahab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    environment:
      UV_LINK_MODE: copy
      PYTHONUNBUFFERED: 1
      HF_HUB_DISABLE_XET: 1
    restart: unless-stopped

  vakilsahab-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    env_file:
      - ./frontend/.env
    container_name: vakilsahab-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
