AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Lambda with Docker

Globals:
  Function:
    MemorySize: 4096
    Timeout: 60
  Api:
    BinaryMediaTypes:
      - "*/*"

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: fastapifunction:fastapi-dev
      Environment:
        Variables:
          DATABASE_URL: your_database_url
          FRONTEND_ORIGIN: http://localhost:3000
          ENVIRONMENT: dev
          GEMINI_API_KEY: your_gemini_api_key
          MISTRAL_API_KEY: your_mistral_api_key
          PINECONE_API_KEY: your_pinecone_api_key
          PINECONE_INDEX_NAME: legal-chatbot-index
          REDIS_URL: your_redis_url
          CLERK_SECRET_KEY: your_clerk_secret_key
          CLERK_FRONTEND_API_URL: your_clerk_frontend_api_url
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
