import {
  IconCorporate,
  IconCriminal,
  IconHome,
  IconPersonalInjury,
  IconRealEstate,
  IconTaxLaw,
} from "@/lib/icons";

export const popularCategories = [
  {
    name: "Family Law",
    tags: ["Divorce", "Custody"],
    Icon: IconHome,
  },
  {
    name: "Corporate",
    tags: ["Business", "Contracts"],
    Icon: IconCorporate,
  },
  {
    name: "Criminal",
    tags: ["Defense", "Appeals"],
    Icon: IconCriminal,
  },
  {
    name: "Personal Injury",
    tags: ["Accidents", "Malpractice"],
    Icon: IconPersonalInjury,
  },
  {
    name: "Tax Law",
    tags: ["Planning", "Disputes"],
    Icon: IconTaxLaw,
  },
  {
    name: "Real Estate",
    tags: ["Property", "Leasing"],
    Icon: IconRealEstate,
  },
];

export const dummyLawyersData = [
  {
    id: "1",
    firstName: "Priya",
    lastName: "Sharma",
    photo: "https://avatar.iran.liara.run/public/85",
    specialization: "Family Lawyer Specialist",
    fees: 4000,
    bio: "15+ years of experience helping families navigate complex legal matters with compassion and expertise.",
    tags: ["Divorce", "Child Custody", "Mediation"],
    rating: 4.9,
    reviews: 128,
  },
  {
    id: "2",
    firstName: "Rahul",
    lastName: "Singh",
    photo: "https://avatar.iran.liara.run/public/25",
    specialization: "Corporate Attorney",
    fees: 16000,
    bio: "Specializing in helping startups and established businesses with legal strategy, contracts, and compliance.",
    tags: ["Contracts", "Business Law", "Mergers"],
    rating: 4.8,
    reviews: 95,
  },
  {
    id: "3",
    firstName: "Anjali",
    lastName: "Gupta",
    photo: "https://avatar.iran.liara.run/public/91",
    specialization: "Criminal Defense Attorney",
    fees: 6000,
    bio: "Aggressive defense attorney with a proven track record of successful case dismissals and favorable outcomes.",
    tags: ["Criminal Defense", "DUI", "Appeals"],
    rating: 4.7,
    reviews: 83,
  },
  {
    id: "4",
    firstName: "Rohan",
    lastName: "Patel",
    photo: "https://avatar.iran.liara.run/public/18",
    specialization: "Real Estate Attorney",
    fees: 5200,
    bio: "Expert in residential and commercial real estate transactions, property disputes, and landlord-tenant matters.",
    tags: ["Property Law", "Leasing", "Zoning"],
    rating: 4.9,
    reviews: 112,
  },
  {
    id: "5",
    firstName: "Aisha",
    lastName: "Khan",
    photo: "https://avatar.iran.liara.run/public/72",
    specialization: "Immigration Attorney",
    fees: 3200,
    bio: "Dedicated to helping individuals and families navigate the complex immigration system with personalized service.",
    tags: ["Visas", "Green Cards", "Citizenship"],
    rating: 4.8,
    reviews: 76,
  },
  {
    id: "6",
    firstName: "Vikram",
    lastName: "Yadav",
    photo: "https://avatar.iran.liara.run/public/45",
    specialization: "Personal Injury Attorney",
    fees: 0,
    bio: "Fighting for maximum compensation for injury victims with a no-win, no-fee guarantee on all personal injury cases.",
    tags: ["Car Accidents", "Medical Malpractice", "Workplace Injuries"],
    rating: 4.7,
    reviews: 92,
  },
];
