name: Backend Destroy

on:
  workflow_dispatch:
  # Uncomment below to auto-deploy on push to master
  # push:
  #   branches:
  #     - master

env:
  AWS_REGION: ap-south-1
  ECR_REPO: vakilsahab-backend
  TF_VAR_database_url: ${{ secrets.DATABASE_URL }}
  TF_VAR_frontend_origin: ${{ secrets.FRONTEND_ORIGIN }}
  TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
  TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
  TF_VAR_mistral_api_key: ${{ secrets.MISTRAL_API_KEY }}
  TF_VAR_pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
  TF_VAR_pinecone_index_name: "vakilsahab-chatbot-index"
  TF_VAR_redis_url: ${{ secrets.REDIS_URL }}
  TF_VAR_clerk_frontend_api_url: ${{ secrets.CLERK_FRONTEND_API_URL }}

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
